### ISSUE TITLE
.

### ISSUE THREAD

**Issue by predators46** [ilya-fedin/pihole-openwrt#2]
.

**Comment by ilya-fedin** [comment]
What file are you talking about? :thinking:

**Comment by predators46** [comment]
> What file are you talking about? 🤔

Pihole openwrt

**Comment by predators46** [comment]
> What file are you talking about? 🤔

how to use it? i am trying to access 192.168.1.1/admin giving me error 503

**Comment by ilya-fedin** [comment]
> Pihole openwrt

It's not a file, it's two words...

**Comment by ilya-fedin** [comment]
> how to use it?

I don't remember... I did this 3 years ago and I switched to AdGuard Home a lot of time ago.

**Comment by predators46** [comment]
> > how to use it?
> 
> I don't remember... I did this 3 years ago and I switched to AdGuard Home a lot of time ago.

I don't really like Adguard. Thank you friends
